name: Nasza nazwa

on: push

jobs:
 tests:
    runs-on: ubuntu-latest
    # Konfiguracja kontenera
    container:
      image: node:20
    steps:
    # Checkout kodu z repozytorium
    - name: Checkout
      uses: actions/checkout@v4 
    # Instalujemy zależności
    - name: Install dependencies
      run: npm install
    # Wykonujemy testy  
    - name: Run tests
      run: npm test
