name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v3
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install

  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v3
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Run unit tests
      run: npm test
